add_test( SortTest.swap /home/nikita/gitu/cmake-example-repo/mybuild/example_tests [==[--gtest_filter=SortTest.swap]==] --gtest_also_run_disabled_tests)
set_tests_properties( SortTest.swap PROPERTIES WORKING_DIRECTORY /home/nikita/gitu/cmake-example-repo/mybuild)
add_test( SortTest.insertion_10 /home/nikita/gitu/cmake-example-repo/mybuild/example_tests [==[--gtest_filter=SortTest.insertion_10]==] --gtest_also_run_disabled_tests)
set_tests_properties( SortTest.insertion_10 PROPERTIES WORKING_DIRECTORY /home/nikita/gitu/cmake-example-repo/mybuild)
add_test( SortTest.insertion_10000 /home/nikita/gitu/cmake-example-repo/mybuild/example_tests [==[--gtest_filter=SortTest.insertion_10000]==] --gtest_also_run_disabled_tests)
set_tests_properties( SortTest.insertion_10000 PROPERTIES WORKING_DIRECTORY /home/nikita/gitu/cmake-example-repo/mybuild)
add_test( SortTest.bubblesort_10 /home/nikita/gitu/cmake-example-repo/mybuild/example_tests [==[--gtest_filter=SortTest.bubblesort_10]==] --gtest_also_run_disabled_tests)
set_tests_properties( SortTest.bubblesort_10 PROPERTIES WORKING_DIRECTORY /home/nikita/gitu/cmake-example-repo/mybuild)
add_test( SortTest.bubblesort_10000 /home/nikita/gitu/cmake-example-repo/mybuild/example_tests [==[--gtest_filter=SortTest.bubblesort_10000]==] --gtest_also_run_disabled_tests)
set_tests_properties( SortTest.bubblesort_10000 PROPERTIES WORKING_DIRECTORY /home/nikita/gitu/cmake-example-repo/mybuild)
add_test( SortTest.quicksort_10 /home/nikita/gitu/cmake-example-repo/mybuild/example_tests [==[--gtest_filter=SortTest.quicksort_10]==] --gtest_also_run_disabled_tests)
set_tests_properties( SortTest.quicksort_10 PROPERTIES WORKING_DIRECTORY /home/nikita/gitu/cmake-example-repo/mybuild)
set( example_tests_TESTS SortTest.swap SortTest.insertion_10 SortTest.insertion_10000 SortTest.bubblesort_10 SortTest.bubblesort_10000 SortTest.quicksort_10)
